### ISSUE TITLE
2.6之后spring-data-redis变成了 Lettuce,如何自定义序列化

### ISSUE THREAD

**Issue by jtxf1** [xymiao/springboot-tutorial#1]

**Comment by xymiao** [comment]
可以参考：
https://docs.spring.io/spring-data/redis/docs/current/reference/html/#reference
和
https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:connectors:lettuce
以及
https://lettuce.io/core/5.3.7.RELEASE/reference/index.html#spring-support

**Comment by jtxf1** [comment]
感谢大佬,都没想到看lettuce官方文档
